name: Deploy
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn eslint . --ext .ts

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn jest

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, tests]
    steps:
      - uses: actions/checkout@v3
      - name: Install Railway CLI
        run: yarn global add @railway/cli
      - name: Deploy to Railway
        run: railway up --service auckland-rubbish-reminder
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}